---
# vars file for role_ec2
  region: "us-east-1"
  vpc_cidr: "10.10.0.0/16"
  subnet_cidr: "10.10.1.0/28"
#  instance_name: "ansible_instance"
  instance_type: "t2.micro"
#  image_id: "ami-053a45fff0a704a47"
#  Environment: "Testing"
  input_list:
    -   { image: "ami-053a45fff0a704a47", name: "linux-1", Environment: "Staging"}
    -   { image: "ami-053a45fff0a704a47", name: "linux-2", Environment: "Staging"}     
    -   { image: "ami-04b4f1a9cf54c11d0", name: "ubuntu-1", Environment: "Prod"}
  key_path: "~/ansible/aws_key.pem"
  rt_tag: "public_route_table"
  sg_rules:
    proto: all
    port: 
      - 80
      - 22
      - 443 
    cidr_ip: "0.0.0.0/0"

  iam_role: "arn:aws:iam::058264145300:user/ansible_user"

