---
- name: wait for ec2 instance to come up
  wait_for:
      timeout: 100

- name: get linux-1 ec2 instance IP
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "linux-1"
  register: ec2_node_info

- set_fact:
    linux_IP: "{{ ec2_node_info.instances[0].public_ip_address }}"

- name: copy key to host
  expect:
    command: "ssh-copy-id -f \"-o IdentityFile {{ key_path }}\" ec2-user@{{ linux_IP }}"
    responses:
      (?i)Are you sure you want to continue connecting: "yes"

- name: get linux-2 ec2 instance IP
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "linux-2"
  register: ec2_node_info

- set_fact:
    linux_IP: "{{ ec2_node_info.instances[0].public_ip_address }}"

- name: copy key to host
  expect:
    command: "ssh-copy-id -f \"-o IdentityFile {{ key_path }}\" ec2-user@{{ linux_IP }}"
    responses:
      (?i)Are you sure you want to continue connecting: "yes"

- name: get ubuntu-1 ec2 instance IP
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "ubuntu-1"
  register: ec2_node_info

- set_fact:
    ubuntu_IP: "{{ ec2_node_info.instances[0].public_ip_address }}"

- name: copy key to host
  expect:
    command: "ssh-copy-id -f \"-o IdentityFile {{ key_path }}\" ubuntu@{{ ubuntu_IP }}"
    responses:
      (?i)Are you sure you want to continue connecting: "yes"

