---
- hosts: all
  tasks:
  - name: Terminate every running instance in a region.
    amazon.aws.ec2_instance:
      state: absent
      region: us-east-1
      filters:
        instance-state-name: running