#https://docs.ansible.com/ansible/latest/collections/amazon/aws/docsite/aws_ec2_guide.html

plugin: amazon.aws.aws_ec2

groups:
  linux: "'Staging' in tags.Environment"
  ubuntu: "'Prod' in tags.Environment"


hostnames:
  - ip-address
