---
- hosts: ubuntu
  become: true
  remote_user: ubuntu
  tasks:
  - name: ping server
    ping:
    register: ping_response

  - debug:
      msg: "{{ ping_response }}"

- hosts: linux
  become: true
  remote_user: ec2-user
  tasks:
  - name: ping server
    ping:
    register: ping_response

  - debug:
      msg: "{{ ping_response }}"

  - hosts: all