apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-tt
  name: nginx-tt
spec:
  containers:
  - image: nginx
    name: nginx-tt
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "group"
    operator: "Equal"
    value: "AI"
    effect: "NoSchedule"
status: {}
