apiVersion: v1
kind: Pod                   # Kubernetes resource type (Pod)
metadata:
  name: nginx-pod2           # Name of the Pod
  labels:
    app: nginx              # Label for the Pod
spec:
  containers:
  - name: nginx-container   # Name of the container inside the Pod
    image: nginx:latest     # Docker image to use
    ports:
    - containerPort: 80     # Port the container listens on
