apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3  # Maintain 3 identical pods at all times
  selector:
    app: nginx  # Must match the pod template's labels
  template:    # Pod template
    metadata:
      name: nginx-pod
      labels:
        app: nginx  # Must match the selector
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
