# If Ansible cannot connect to a host, it marks that host as ‘UNREACHABLE’ and removes it from the list of active hosts for the run
#  You can use meta: clear_host_errors to reactivate all hosts, so subsequent tasks can try to reach them again
#---------------------------------------------------------------------------------------
# You can ignore a task failure due to the host instance being ‘UNREACHABLE’ with the ignore_unreachable keyword. 
# Ansible ignores the task errors but continues to execute future tasks against the unreachable host.


#    run:     ansible-playbook -i ./inventory_unreachable ignore_unreachable.yml 
---
- hosts: all
  become: true
  ignore_unreachable: true    # play level
  tasks:
  - name: get hostname details
    gather_facts:
 #  ignore_unreachable: true  # task level

  - name: get file list
    shell: ls /home/vmadmin/dir
    register: output

  - name: print hostname
    debug:
      msg: "{{ output }}"

